### PR TITLE
Portuguese update (pt_PT)

### PR DESCRIPTION
**Pull request by pedro-mendonca**
As I don't know how you're currently managing language files because they're currently here at GitHub and on WordPress repo, so I'm pulling this update here and I've updated the strings in https://translate.wordpress.org/locale/pt/default/wp-plugins/wp-photo-sphere

### CODE REVIEW

**Comment by JeremyHeleine** [comment]
Hi,

Thanks for this translation! Actually, I don't really understand why WP.org detects the Portuguese translation and not the others. Maybe I did something wrong, I'll see.

I want to have the complete plugin here, with all the available translations, so I think it's better to pull it here. Then I create a new small update to indicate to other users that the translation has been updated and all the repositories are up-to-date. Also I didn't receive any notification for the update on WP.org… Weird.

Anyway, thank you again!

**Comment by pedro-mendonca** [comment]
What do you mean by WP detects?
Portuguese (pt_PT) translation is 100% on the WP repo, so it is available to everyone who updates translation of the plugin, independently of it's release cycle.

**Comment by JeremyHeleine** [comment]
There's surely something I missed, I was sure that the translation files
were taken from the stable repo. As the Portuguese translation appears on
the plugin's page, I thought that WP.org detected it. Pretty naive I guess!

**Comment by pedro-mendonca** [comment]
I'm not sure but I think the Portuguese in the available languages down below is about the translation of the readme file, as some strings are translated, the plugin directory interface of WP-Photo-Sphere becomes available in this language, and listed there.
This is all new, and developing fast, I'm not quite sure how WP manages translation files. For now I guess it gets the translation files on the repo of the plugin, and if it's 100% for a used language it gets an update immediately, but these language files obtained from translate.wordpress.org go to wp-includes/languages/plugins (or themes). Than, probably WordPress gives it priority over the ones loaded originally in plugins/wp-photo-sphere/languages.

**Pull request merged**
